In [41]:
import pandas as pd

In [42]:
datos = pd.read_csv('alquiler_sin_not_null.csv', sep = ';')

In [43]:
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0

In [44]:
#crando variable con espacios, suma de 3 valores ejemplo
#datos['Valor Bruto'] = () + () + ()
datos['Valor Bruto'] = (datos['Valor']) + (datos['Mantenimiento']) + (datos['Impuesto'])
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor Bruto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,2260.0
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,7000.0
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,1210.0
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,1030.0
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,1618.0
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0,22000.0
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0,1000.0
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0,2216.0
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0,1969.0
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0,2611.0

In [45]:
#valor por metro cuadrado
datos['Valor m2'] = (datos['Valor']) / (datos['Area'])
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor Bruto,Valor m2
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,2260.0,42.500000
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,7000.0,70.000000
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,1210.0,53.333333
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,1030.0,16.666667
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,1618.0,26.000000
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0,22000.0,29.333333
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0,1000.0,15.384615
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0,2216.0,21.428571
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0,1969.0,16.666667
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0,2611.0,50.000000

In [46]:
#valor por metro cuadrado, redondeado
datos['Valor m2'] = datos['Valor m2'].round(2)
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor Bruto,Valor m2
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,2260.0,42.50
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,7000.0,70.00
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,1210.0,53.33
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,1030.0,16.67
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,1618.0,26.00
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0,22000.0,29.33
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0,1000.0,15.38
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0,2216.0,21.43
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0,1969.0,16.67
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0,2611.0,50.00

In [47]:
#cradno valor bruto m2 y redondeandolo en una sola variable
datos['Valor Bruto m2'] = ((datos['Valor Bruto']) / (datos['Area'])).round(2)
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor Bruto,Valor m2,Valor Bruto m2
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,2260.0,42.50,56.50
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,7000.0,70.00,70.00
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,1210.0,53.33,80.67
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,1030.0,16.67,21.46
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,1618.0,26.00,32.36
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0,22000.0,29.33,29.33
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0,1000.0,15.38,15.38
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0,2216.0,21.43,31.66
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0,1969.0,16.67,21.88
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0,2611.0,50.00,65.28

In [48]:
#modificando tipos
casa = ['Casa', 'Casda en condominio', 'Casa de villa']

In [49]:
datos['Tipo Agrupado'] = datos['Tipo'].apply(lambda x: 'Casa' if x in casa else 'Departamento')
datos

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor Bruto,Valor m2,Valor Bruto m2,Tipo Agrupado
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,2260.0,42.50,56.50,Departamento
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,7000.0,70.00,70.00,Casa
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,1210.0,53.33,80.67,Departamento
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,1030.0,16.67,21.46,Departamento
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,1618.0,26.00,32.36,Departamento
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22086,Departamento,Santa Anita,2,0,0,70,900.0,490.0,48.0,1438.0,12.86,20.54,Departamento
22087,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0,1175.0,29.63,43.52,Departamento
22088,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0,2640.0,23.08,33.85,Departamento
22089,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0,1946.0,29.17,40.54,Departamento
22090,Departamento,Rímac,2,0,0,70,3000.0,760.0,0.0,3760.0,42.86,53.71,Departamento

#excluyendo variables

In [50]:
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor Bruto,Valor m2,Valor Bruto m2,Tipo Agrupado
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,2260.0,42.50,56.50,Departamento
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,7000.0,70.00,70.00,Casa
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,1210.0,53.33,80.67,Departamento
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,1030.0,16.67,21.46,Departamento
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,1618.0,26.00,32.36,Departamento
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0,22000.0,29.33,29.33,Departamento
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0,1000.0,15.38,15.38,Departamento
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0,2216.0,21.43,31.66,Departamento
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0,1969.0,16.67,21.88,Departamento
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0,2611.0,50.00,65.28,Departamento

In [51]:
#creando dataFrame con informacion disponible
datos_aux = pd.DataFrame(datos[['Tipo Agrupado', 'Valor m2', 'Valor Bruto', 'Valor Bruto m2']])
datos_aux.head(10)

  Tipo Agrupado  Valor m2  Valor Bruto  Valor Bruto m2
0  Departamento     42.50       2260.0           56.50
1          Casa     70.00       7000.0           70.00
2  Departamento     53.33       1210.0           80.67
3  Departamento     16.67       1030.0           21.46
4  Departamento     26.00       1618.0           32.36
5  Departamento     29.33      22000.0           29.33
6  Departamento     15.38       1000.0           15.38
7  Departamento     21.43       2216.0           31.66
8  Departamento     16.67       1969.0           21.88
9  Departamento     50.00       2611.0           65.28

In [52]:
#eliminando variables, primer metodo del
del datos_aux['Valor Bruto']
datos_aux.head(10)

  Tipo Agrupado  Valor m2  Valor Bruto m2
0  Departamento     42.50           56.50
1          Casa     70.00           70.00
2  Departamento     53.33           80.67
3  Departamento     16.67           21.46
4  Departamento     26.00           32.36
5  Departamento     29.33           29.33
6  Departamento     15.38           15.38
7  Departamento     21.43           31.66
8  Departamento     16.67           21.88
9  Departamento     50.00           65.28

In [53]:
#segundo metodo pop
datos_aux.head(10)

  Tipo Agrupado  Valor m2  Valor Bruto m2
0  Departamento     42.50           56.50
1          Casa     70.00           70.00
2  Departamento     53.33           80.67
3  Departamento     16.67           21.46
4  Departamento     26.00           32.36
5  Departamento     29.33           29.33
6  Departamento     15.38           15.38
7  Departamento     21.43           31.66
8  Departamento     16.67           21.88
9  Departamento     50.00           65.28

In [54]:
datos_aux.pop('Valor Bruto m2')

0        56.50
1        70.00
2        80.67
3        21.46
4        32.36
         ...
22086    20.54
22087    43.52
22088    33.85
22089    40.54
22090    53.71
Name: Valor Bruto m2, Length: 22091, dtype: float64

In [55]:
datos_aux.head(10)

  Tipo Agrupado  Valor m2
0  Departamento     42.50
1          Casa     70.00
2  Departamento     53.33
3  Departamento     16.67
4  Departamento     26.00
5  Departamento     29.33
6  Departamento     15.38
7  Departamento     21.43
8  Departamento     16.67
9  Departamento     50.00

In [29]:
#tercer metodo para borrar drop

In [56]:
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor Bruto,Valor m2,Valor Bruto m2,Tipo Agrupado
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,2260.0,42.50,56.50,Departamento
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,7000.0,70.00,70.00,Casa
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,1210.0,53.33,80.67,Departamento
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,1030.0,16.67,21.46,Departamento
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,1618.0,26.00,32.36,Departamento
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0,22000.0,29.33,29.33,Departamento
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0,1000.0,15.38,15.38,Departamento
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0,2216.0,21.43,31.66,Departamento
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0,1969.0,16.67,21.88,Departamento
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0,2611.0,50.00,65.28,Departamento

In [57]:
#si son columnas tengo que usar el metodo axis
datos.drop(['Valor Bruto', 'Valor Bruto m2'], axis = 1, inplace = True)

In [58]:
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto,Valor m2,Tipo Agrupado
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0,42.50,Departamento
1,Casa,Lurigancho,2,0,1,100,7000.0,0.0,0.0,70.00,Casa
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0,53.33,Departamento
3,Departamento,Ate,1,0,0,48,800.0,230.0,0.0,16.67,Departamento
4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0,26.00,Departamento
5,Casa en condominio,Ate,5,4,5,750,22000.0,0.0,0.0,29.33,Departamento
6,Casa en condominio,El Agustino,2,2,0,65,1000.0,0.0,0.0,15.38,Departamento
7,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0,21.43,Departamento
8,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0,16.67,Departamento
9,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0,50.00,Departamento

In [59]:
#exportando csv
datos.to_csv('alquiler_residencial_nuevos_val.csv', sep = ';', index = False)