#Reporte de analisis V

In [ ]:
import pandas as pd

In [ ]:
datos = pd.read_csv('alquiler_residencial.csv',sep = ';')

In [ ]:
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
5,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
6,Casa en condominio,Ate,5,4,5,750,22000.0,NaN,NaN
7,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
8,Departamento,Pachacámac,1,0,0,36,1200.0,NaN,NaN
9,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0

In [ ]:
#Seleccione solamente los inmuebles clasificados como tipo 'Departamennto'

In [ ]:
seleccion = datos['Tipo'] == 'Departamento'
n1 = datos[seleccion].shape[0]
n1

19532

In [ ]:
n1.shape[0]

19532

In [ ]:
#Seleccione los inmuebles clasificados como tipo 'Casa', 'Casa en condominio' y 'Casa de villa'

In [ ]:
seleccion = (datos['Tipo'] == 'Casa') | (datos['Tipo'] == 'Casa en condominio') | (datos['Tipo'] == 'Casa de villa')

In [ ]:
n2 = datos[seleccion].shape[0]
n2

2212

In [ ]:
#Seleccione los inmuebles con area entre 60 y 100 metros cuadrados, incluyendo los limites

In [ ]:
seleccion = (datos['Area'] >=60) & (datos['Area'] <=100)
n3 = datos[seleccion].shape[0]
n3

8736

In [ ]:
n3

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
7,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
9,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0
10,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0
...,...,...,...,...,...,...,...,...,...
22833,Departamento,Jesús María,3,2,1,88,1550.0,790.0,NaN
22835,Departamento,Rímac,3,0,1,80,3000.0,1010.0,249.0
22840,Departamento,Santa Anita,2,0,0,70,900.0,490.0,48.0
22842,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
22844,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN

In [ ]:
#Seleccione los inmuebles que tengan por lo menos 4 cuarts y alquiler menor que $2.000,00

In [ ]:
seleccion = (datos['Cuartos'] >=4) & (datos['Valor'] <=2000)
n4 = datos[seleccion].shape[0]
n4

60

In [ ]:
print("N° de inmuebles clasificados como tipo 'Departamennto' -> {}".format(n1))
print("N° de inmuebles clasificados como tipo 'Casa', 'Casa en condominio' y 'Casa de villa' -> {}".format(n2))
print("N° de inmuebles con area entre 60 y 100 metros cuadrados, incluyendo los limites' -> {}".format(n3))
print("N° de inmuebles que tengan por lo menos 4 cuarts y alquiler menor que $2.000,00 -> {}".format(n4))

N° de inmuebles clasificados como tipo 'Departamennto' -> 19532
N° de inmuebles clasificados como tipo 'Casa', 'Casa en condominio' y 'Casa de villa' -> 2212
N° de inmuebles con area entre 60 y 100 metros cuadrados, incluyendo los limites' -> 8736
N° de inmuebles que tengan por lo menos 4 cuarts y alquiler menor que $2.000,00 -> 60